ALTER TABLE SR_CLIENTI
  ADD CONSTRAINT pk_sr_clienti PRIMARY KEY (id_client);

ALTER TABLE SR_MASINI
  ADD CONSTRAINT pk_sr_masini PRIMARY KEY (id_masina);

ALTER TABLE SR_ANGAJATI
  ADD CONSTRAINT pk_sr_angajati PRIMARY KEY (id_angajat);

ALTER TABLE SR_VANZARI
  ADD CONSTRAINT pk_sr_vanzari PRIMARY KEY (id_vanzare);

ALTER TABLE SR_TESTDRIVE
  ADD CONSTRAINT pk_sr_testdrive PRIMARY KEY (id_test);

ALTER TABLE SR_PLATI
  ADD CONSTRAINT pk_sr_plati PRIMARY KEY (id_plata);

ALTER TABLE SR_VANZARI
  ADD CONSTRAINT fk_vanz_client FOREIGN KEY (id_client)
  REFERENCES SR_CLIENTI(id_client);

ALTER TABLE SR_VANZARI
  ADD CONSTRAINT fk_vanz_masina FOREIGN KEY (id_masina)
  REFERENCES SR_MASINI(id_masina);

ALTER TABLE SR_VANZARI
  ADD CONSTRAINT fk_vanz_angajat FOREIGN KEY (id_angajat)
  REFERENCES SR_ANGAJATI(id_angajat);

ALTER TABLE SR_TESTDRIVE
  ADD CONSTRAINT fk_test_client FOREIGN KEY (id_client)
  REFERENCES SR_CLIENTI(id_client);

ALTER TABLE SR_TESTDRIVE
  ADD CONSTRAINT fk_test_masina FOREIGN KEY (id_masina)
  REFERENCES SR_MASINI(id_masina);

ALTER TABLE SR_PLATI
  ADD CONSTRAINT fk_plata_vanzare FOREIGN KEY (id_vanzare)
  REFERENCES SR_VANZARI(id_vanzare);

ALTER TABLE SR_MASINI
  ADD CONSTRAINT ck_sr_masini_status
  CHECK (status IN ('DISPONIBILA','VANDUTA'));

ALTER TABLE SR_PLATI
  ADD CONSTRAINT ck_sr_plata_suma
  CHECK (suma > 0);

ALTER TABLE SR_CLIENTI
  MODIFY email VARCHAR2(80);

ALTER TABLE SR_MASINI
  ADD CONSTRAINT ck_sr_masini_an
  CHECK (an_fabricatie BETWEEN 1970 AND 2025);
